FROM platforme/python:latest

LABEL version="1.0"
LABEL maintainer="Platforme <development@platforme.com>"

EXPOSE 8080

ENV LEVEL INFO
ENV ENCODING gzip
ENV HOST 0.0.0.0
ENV PORT 8080
ENV CACHE 86400
ENV INDEX_FILES index.html
ENV CORS 1
ENV BASE_PATH /src/.vuepress/dist

ADD documentation /

RUN apk update && apk add --no-cache nodejs npm
RUN pip3 install --upgrade netius
RUN npm install
RUN npm run build

CMD ["/usr/bin/python3", "-m", "netius.extra.filea"]
