name: Deploy Workflow
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Deploy
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [10]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: npm install
      - run: npm install --only=dev
      - run: npm install canvas --no-save
      - run: npm run build
      - run: npm run lint
      - run: npm test
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_KEY: ${{ secrets.TEST_KEY }}
          MAX_SOCKETS: ${{ secrets.MAX_SOCKETS }}
          SKIP_TEST_NOTIFY: 1
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
